[package]
name = "website"
version = "0.1.0"
authors = ["Мира Странная <miraityan2004@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "3", features = ["openssl"] }
actix-files = "0.5"
actix-rt = "1"
tera = "1"
rusqlite = "0.25"
chrono = "0.4"
time = "0.1"
openssl = "0.10"
serde_json = "1"
serde = "1"
env_logger = "0.8"
geoip2 = "0.1.6"
